### PR TITLE
Adding Dynamic Contributors and fixes #45

### LINKED ISSUE #45: Contributors Image In Readme
I think it is a great feature to add contributors image in README file. It really motivate to contributors. It is dynamically order the contributors. 

contrimga

If you want to this feature on README so I want to do this issue !! 😄

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
Now you don't need to add contributor manually. This will fixes #45 .

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
@PragatiVerma18 Please Review and merge this PR.!!

**Review by PragatiVerma18 — APPROVED** [review]
Looks good to me! Thanks for the PR @Vishal-raj-1

**Comment by Vishal-raj-1** [comment]
Please update my score in NWOC for opening one issue and for one PR. @PragatiVerma18

**Comment by Vishal-raj-1** [comment]
> Please update my score in NWOC for opening two issue and one PR. @PragatiVerma18

@PragatiVerma18  ??

**Comment by PragatiVerma18** [comment]
> > Please update my score in NWOC for opening two issue and one PR. @PragatiVerma18
> 
> @PragatiVerma18 ??

I have already updated your score. Please do check.

**Comment by Vishal-raj-1** [comment]
> I have already updated your score. Please do check.

Thanks for the update.

**Pull request merged**
