### PR TITLE
Made a new stylesheet files

### PR DESCRIPTION
**Pull request by sagarpandyansit**
**Issue that resolved:**
https://github.com/PragatiVerma18/Snippet-Share/issues/60

**Solution:**
Put all styles in a separate file for better readability and directory structure.

### CODE REVIEW

**Comment by sagarpandyansit** [comment]
@PragatiVerma18, Kindly review it.

**Review by PragatiVerma18 — COMMENTED** [review]
Please attach some screenshots so as to give an idea of the style changes, if any.

**Comment by sagarpandyansit** [comment]
@PragatiVerma18, I did not change anything. I literally copied all styles that were written in the HTML file to the new CSS file and link them. As style and script should not be in the HTML file. I just made the directory and file structure better. Nothing else.

**Review by PragatiVerma18 — CHANGES_REQUESTED** [review]
Please push the changes to the `nwoc` branch to get it merged.

**Comment by sagarpandyansit** [comment]
@PragatiVerma18, I have changed the base branch. Kindly merge with the SWoC label. Thanks.

**Review by PragatiVerma18 — APPROVED** [review]
Looks good to me! Thanks for dropping this PR.

**Pull request merged**
